var mongoose = require('mongoose');
var validator = require('validator');
var Schema = mongoose.Schema,

ObjectId = Schema.ObjectId;
var myuser = new Schema({
user_name :String,
user_email :String,
user_mobile :String,
uname:String,
user_enquiry: String,
uname :String,
city1 :String,
city2:String,
city3:String,
//lettr
uaddress :String,
mobile:String,
date:String,
office_city:String,
//namunae12
// uname: req.body.uname,
fname:String,
// uaddress: req.body.uaddress,
dob:String ,
dobplace:String,
education:String ,
experience:String ,
height: String,
symbol:String ,
color:String,
//namunae
worktype:String,
// uname: req.body.uname,
designation: String,
joiningdate: String,
livingdate: String,
supervisorname:String,
companyname:String,
licenseno:String,
regdetail:String,
// date:req.body.companyname
//prapatra
// uname: String,
// fname: String,
age: String,
year: String,
//namunac
occupation: String,
adharno:String,
chalandate:String,
chalanplace:String,
// firmname:String,
period:String,
chalanno:String,
rupee:String,
place:String,
language:String,
examcenter:String,
//namunab1
// education:String,
duration:String,
institutename:String,
instituteplace:String,
state:String,
//wireman-suit-namuna12
            seatno:String,
            examdate:String,
            examplace:String,
            result:String,
            examname:String,
            examexperience:String,
            // height:String,
            // symbol:String,
            // color:String,
            // period:String,
            lastexperience:String,
            lastplace:String,

            //newContractorLicense
            city4:String,
            firmName:String,
            supervisorLicenseNo:String,
            supervisorLicenseDate:String,
            supervisorName:String,
            ownerName:String,
            megarMake:String,
            megarNo:String,
            earthTesterMake:String,
            earthTesterNo:String,
            chalanNo:String,
            chalanDate:String,
            megarReceiptNo:String,
            megarReceiptDate:String,
            earthTesterReceiptNo:String,
            earthTesterReceiptDate:String,
            earthTesterReceiptNo:String,
            ownerAddress:String,
            supervisorAddress:String,
            supervisorMobile:String,
            //new contractor namuna e
            firmAddress:String,
            ownerMobile:String,
            ownerEmail:String,
            partnership:String,
            ownerDob:String,
            ownerAge:String,
            ownerFname:String,
            ownerEducation:String,
            partnerName:String,
            partnerAddress:String,
            bankName:String,
            accountNo:String,
            balance:String,
            previousLicenseNo:String,
            licenseValidity:String,
            workDetails:String,
            reason:String,
            shopName:String,
            billNo:String,
            billDate:String,
            district:String,
//namuna-s
      sanctionDate:String,
      megarRenewalPeriod:String,
      earthTesterRenewalPeriod:String,
      supervisorEmail:String,
      partnerName:String,
      partnerAddress:String,
      partnerEmail:String,
      partnerMobile:String,

      lastFirm:String,
      lastFirmAddress:String,
      lastFirmNo:String,
      firmPeriodFrom:String,
      firmPeriodTo:String,

      supervisorAge:String,
      supervisorAdharNo:String,
      licensePeriod:String,
      firmRegNo:String,
      licensePeriodFrom:String,
      licensePeriodTo:String,
      city5:String,
      city6:String,
      city7:String,
      sanctionNo:String,

      customerName:String,
      customerAddress:String,
      workStartDate:String,
      workEndDate:String,
      wiremanName:String,
      reportDate:String,
      supplyCompanyName:String,
      powerSupplyDate:String,
      powerSupplyPerson:String,
      powerSupplyNo:String,
      shera:String,
      ownerAdharNo:String,
      ownerOccupation:String,
      supervisorOccupation:String,
      supervisorFname:String,

      customerName1: String,
      customerAddress1: String,
      workStartDate1: String,
      workEndDate1: String,
      wiremanName1: String,
      reportDate1: String,
      supplyCompanyName1: String,
      powerSupplyDate1: String,
      powerSupplyPerson1: String,
      powerSupplyNo1: String,
      shera1: String,
      
      customerName2: String,
      customerAddress2: String,
      workStartDate2: String,
      workEndDate2: String,
      wiremanName2: String,
      reportDate2: String,
      supplyCompanyName2: String,
      powerSupplyDate2: String,
      powerSupplyPerson2: String,
      powerSupplyNo2: String,
      shera2: String,

      customerName3: String,
      customerAddress3: String,
      workStartDate3: String,
      workEndDate3: String,
      wiremanName3: String,
      reportDate3: String,
      supplyCompanyName3: String,
      powerSupplyDate3: String,
      powerSupplyPerson3: String,
      powerSupplyNo3: String,
      shera3: String,

      customerName4: String,
      customerAddress4: String,
      workStartDate4: String,
      workEndDate4: String,
      wiremanName4: String,
      reportDate4: String,
      supplyCompanyName4: String,
      powerSupplyDate4: String,
      powerSupplyPerson4: String,
      powerSupplyNo4: String,
      shera4: String,


      
      customerName5: String,
      customerAddress5: String,
      workStartDate5: String,
      workEndDate5: String,
      wiremanName5: String,
      reportDate5: String,
      supplyCompanyName5: String,
      powerSupplyDate5: String,
      powerSupplyPerson5: String,
      powerSupplyNo5: String,
      shera5: String,


      customerName6: String,
      customerAddress6: String,
      workStartDate6: String,
      workEndDate6: String,
      wiremanName6: String,
      reportDate6: String,
      supplyCompanyName6: String,
      powerSupplyDate6: String,
      powerSupplyPerson6: String,
      powerSupplyNo6: String,
      shera6: String,

      customerName7: String,
      customerAddress7: String,
      workStartDate7: String,
      workEndDate7: String,
      wiremanName7: String,
      reportDate7: String,
      supplyCompanyName7: String,
      powerSupplyDate7: String,
      powerSupplyPerson7: String,
      powerSupplyNo7: String,
      shera7: String,
      
      customerName8: String,
      customerAddress8: String,
      workStartDate8: String,
      workEndDate8: String,
      wiremanName8: String,
      reportDate8: String,
      supplyCompanyName8: String,
      powerSupplyDate8: String,
      powerSupplyPerson8: String,
      powerSupplyNo8: String,
      shera8: String,
        ifpartnerName:String,
      ifpartnerAddress:String,
      examPeriod:String,
      username:String,
      
      //       city4:String,
      //       mesars:String,
      //       licenseNo:String,
      //       licenseDate:String,
      //       supervisorName:String,
      //       owner:String,
      //       megar:String,
      //       megarNo:String,
      //       earthTester:String,
      //       earthTesterNo:String,
      //       chalanDate:String,
      //       chalanNo:String,

      //       instituteName:String,
      // instituteAddress:String,
      // partnership:String,
      // bankDetails:String,
      // shopName:String,
      // billNo:String,
      // billDate:String,
      // megarYear:String,
      // earthYear:String,


},
{ typeKey: '$type' });
module.exports = mongoose.model('user', myuser);

// var mylogin = new Schema({
//     user_uname :String,
//     user_pswd :String
//     });
//     module.exports = mongoose.model('login', mylogin);